files:
  - pkg/features/kube_features.go
  - pkg/features/versioned_kube_features.go
  - staging/src/k8s.io/apiserver/pkg/features/kube_features.go
  - staging/src/k8s.io/client-go/features/known_features.go
  - staging/src/k8s.io/controller-manager/pkg/features/kube_features.go
  - staging/src/k8s.io/apiextensions-apiserver/pkg/features/kube_features.go
  - test/e2e/feature/feature.go
  - test/e2e/environment/environment.go
